[project]
name = "ai-insurance-claim-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thubalethu Njapha", email = "thubzthubz@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.4.0",
    "openai>=3.22.1",
    "python-dotenv>=1.2.4",
]

[project.scripts]
ai-insurance-claim-analyzer = "ai_insurance_claim_analyzer:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
